name: Releases

on:
  push:
    branches:
      - 'main'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./version.txt
    - name: Echo package.json
      run: echo "${{ steps.version.outputs.content }}"
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.version.outputs.content }}"
        artifacts: "${{ steps.version.outputs.content }}.zip"
