name: Releases

on:
  push:
    branches:
      - 'main'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./version.txt
    - name: Echo version
      run: echo "${{ steps.version.outputs.content }}"
    - name: Calculate version
      id: new-version
      run: echo "TAG_NAME=$(echo $(($(cat ./version.txt | grep -E '[0-9]') + 1)))" >> $GITHUB_OUTPUT
    - name: Change version
      uses: DamianReeves/write-file-action@master
      with:
        path: ./version.txt
        contents: |
          "v${{ steps.new-version.outputs.TAG_NAME }}"
        write-mode: overwrite
    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        message: ':bookmark: v${{ steps.new-version.outputs.TAG_NAME }}'
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ steps.new-version.outputs.TAG_NAME }}"
        # artifacts: "v${{ steps.new-version.outputs.TAG_NAME }}.zip"
